// 프리뷰용 더미 데이터 (GitHub Pages 정적 배포에서 API 대신 사용)

export const DUMMY_CONTENTS = [
  {
    id: 'demo-1',
    title: '서울 야경 시네마틱 4K',
    description: '남산타워, 한강, 강남 스카이라인을 담은 시네마틱 야경 영상 소스',
    category: '도시/야경',
    gdrive_folder_id: '',
    thumbnail_url: null,
    release_order: 1,
    is_public: true,
    created_at: '2026-01-01T00:00:00Z',
    unlocked: true,
    file_count: 5,
  },
  {
    id: 'demo-2',
    title: '제주 자연 드론샷',
    description: '성산일출봉, 협재해변, 한라산 드론 촬영 영상 소스',
    category: '자연/풍경',
    gdrive_folder_id: '',
    thumbnail_url: null,
    release_order: 2,
    is_public: false,
    created_at: '2026-01-04T00:00:00Z',
    unlocked: true,
    file_count: 8,
  },
  {
    id: 'demo-3',
    title: '카페 인테리어 B-Roll',
    description: '감성 카페 인테리어, 라떼아트, 디저트 클로즈업',
    category: '라이프스타일',
    gdrive_folder_id: '',
    thumbnail_url: null,
    release_order: 3,
    is_public: false,
    created_at: '2026-01-07T00:00:00Z',
    unlocked: true,
    file_count: 6,
  },
  {
    id: 'demo-4',
    title: '스트릿 패션 슬로모션',
    description: '홍대, 성수동 스트릿 패션 슬로모션 촬영',
    category: '패션/뷰티',
    gdrive_folder_id: '',
    thumbnail_url: null,
    release_order: 4,
    is_public: false,
    created_at: '2026-01-10T00:00:00Z',
    unlocked: false,
    file_count: 4,
  },
  {
    id: 'demo-5',
    title: '음식 클로즈업 ASMR',
    description: '한식, 양식, 일식 요리 과정 및 플레이팅 클로즈업',
    category: '푸드',
    gdrive_folder_id: '',
    thumbnail_url: null,
    release_order: 5,
    is_public: false,
    created_at: '2026-01-13T00:00:00Z',
    unlocked: false,
    file_count: 7,
  },
  {
    id: 'demo-6',
    title: '오피스 워킹 모션',
    description: '현대적 오피스 환경, 타이핑, 회의실, 코워킹 스페이스',
    category: '비즈니스',
    gdrive_folder_id: '',
    thumbnail_url: null,
    release_order: 6,
    is_public: false,
    created_at: '2026-01-16T00:00:00Z',
    unlocked: false,
    file_count: 5,
  },
  {
    id: 'demo-7',
    title: '벚꽃 시즌 타임랩스',
    description: '여의도, 석촌호수 벚꽃 개화 타임랩스 + 산책 영상',
    category: '자연/풍경',
    gdrive_folder_id: '',
    thumbnail_url: null,
    release_order: 7,
    is_public: false,
    created_at: '2026-01-19T00:00:00Z',
    unlocked: false,
    file_count: 3,
  },
  {
    id: 'demo-8',
    title: '피트니스 트레이닝',
    description: '헬스장 웨이트 트레이닝, 요가, 러닝 촬영 소스',
    category: '스포츠/건강',
    gdrive_folder_id: '',
    thumbnail_url: null,
    release_order: 8,
    is_public: false,
    created_at: '2026-01-22T00:00:00Z',
    unlocked: false,
    file_count: 6,
  },
  {
    id: 'demo-9',
    title: '한옥 감성 인테리어',
    description: '북촌, 전주 한옥마을 전통 건축 디테일 촬영',
    category: '건축/인테리어',
    gdrive_folder_id: '',
    thumbnail_url: null,
    release_order: 9,
    is_public: false,
    created_at: '2026-01-25T00:00:00Z',
    unlocked: false,
    file_count: 4,
  },
];

// 더미 파일 목록 (콘텐츠별)
export const DUMMY_FILES: Record<string, Array<{ id: string; content_id: string; filename: string; gdrive_file_id: string; file_size: number; mime_type: string; created_at: string }>> = {
  'demo-1': [
    { id: 'f1-1', content_id: 'demo-1', filename: '금광롱폼_1.mp4', gdrive_file_id: '1YT4OID5jDJWIbZwkSyP1zovyckbXJseI', file_size: 307232768, mime_type: 'video/mp4', created_at: '2026-01-01T00:00:00Z' },
    { id: 'f1-2', content_id: 'demo-1', filename: '녹화_2025_10_26.mp4', gdrive_file_id: '1NFTyRfE3QK_gqYXQQ1kS6hxJBNFaQad5', file_size: 715128832, mime_type: 'video/mp4', created_at: '2026-01-01T00:00:00Z' },
  ],
  'demo-2': [
    { id: 'f2-1', content_id: 'demo-2', filename: 'jeju_drone_sunrise_4K.mp4', gdrive_file_id: '', file_size: 712300000, mime_type: 'video/mp4', created_at: '2026-01-04T00:00:00Z' },
    { id: 'f2-2', content_id: 'demo-2', filename: 'jeju_drone_beach_4K.mp4', gdrive_file_id: '', file_size: 623400000, mime_type: 'video/mp4', created_at: '2026-01-04T00:00:00Z' },
  ],
  'demo-3': [
    { id: 'f3-1', content_id: 'demo-3', filename: 'cafe_interior_01.mp4', gdrive_file_id: '', file_size: 312000000, mime_type: 'video/mp4', created_at: '2026-01-07T00:00:00Z' },
    { id: 'f3-2', content_id: 'demo-3', filename: 'cafe_latte_art.mp4', gdrive_file_id: '', file_size: 198000000, mime_type: 'video/mp4', created_at: '2026-01-07T00:00:00Z' },
  ],
};

export const DUMMY_STATS = {
  totalUsers: 47,
  activeSubscriptions: 12,
  totalContents: 9,
  monthlyDownloads: 234,
};
